### ISSUE TITLE
Wrong index using

### ISSUE THREAD

**Issue by akabuda050** [VelbazhdSoftwareLLC/BugABoomSimulator#1]
Hi, seems like you use wrong index for win variable on wild win. I guess it should be the "2"

https://github.com/VelbazhdSoftwareLLC/BugABoomSimulator/blob/e8d66ff2cb57f0ca984ce77cd2806675dd086107/Main.cs#L503

**Comment by TodorBalabanov** [comment]
@akabuda050 Yes. You are correct. It was wrong. 

Bug A Boom was proposed by one of Bulgarian slot mathematicians. My simulation was done just for doing something in my free time.

**Comment by akabuda050** [comment]
I see. Thanks. In any case this simulation helped me to understand some basic principles of slots machines.

In addition, there is a small issue too
https://github.com/VelbazhdSoftwareLLC/BugABoomSimulator/blob/e8d66ff2cb57f0ca984ce77cd2806675dd086107/Main.cs#L544
This line takes elements vertically, seems like you need to use `view[index][i]`. What do you think?

**Comment by TodorBalabanov** [comment]
Have you tried to compile it as `view[index][i]`? I think it will give an array index out of bounds exception. 

Have you looked at my other repositories? There are many other slot machine source codes.

**Comment by akabuda050** [comment]
Heh, it took a long time to get back to it. thanks one more time!

I didn't try to compile it, I just made some JavaScript analog with UI https://github.com/akabuda050/megaslot

**Comment by TodorBalabanov** [comment]
Thanks. I will take a look.
